spring:
  jpa:
    # 전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # 테스트 실행 후 테이블이 자동 삭제
        ddl-auto: create-drop

    # 테이블 생성 후에 data.sql 실행
    defer-datasource-initialization: true
